### ISSUE TITLE
implement state-specific status pages

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#3]
after #1

**Comment by jamesturk** [comment]
possibly w/ additional drilldown / filtering by session/etc.

**Comment by hiteshgarg14** [comment]
Since We have covered many things in DataQuality Section. So here are some thoughts regarding state-specific status page

1. Legislators Page
    - On overview page of a particular state, we can have a button `View All` (linked to a django-admin page to list all people for that  state.)
   - Inactive Legislators - We don't have them yet.
   - One thought is to show Inserted/Updated/Noop Count related complied data in graph/numbers format on this page. but since we have `Run Detail` page already so this info can be shown there.

2. Organization Page
   - On overview page of a particular state, we can have a button `View All` (linked to Django-admin page to list all organizations for that  state.)
   - In Billy admin, we have the option to delete a committee that is now available with Django-admin.
   - inserted/Updated/Noop Count related complied data either on Run Detail page or on this page.
   - ( If this info is important then) we can show a list of all available `classification` with their count with them and link to Django-admin. for eg.  `admin/core/organization/?classification=upper` etc. but at the same time, we can show this list with their count on the dropdown in the navbar to avoid having a separate page for it.
   -  Posts - confused about it. ???
   -  can list all votes etc. (but I believe that this is something related to openstates.org)

3. Bill Page
   - On overview page of a particular state, we can have a button `View All` (linked to Django-admin page to list all bills for that  state.)
   -  On Navbar dropdown, there will a list of all legislative sessions when the user clicks on any one of them then a new page will open and there will be info like:-
              - `Bill Counts`, `Bill Types`, `Actions by Type`, `Actions by Actor` [from Billy admin] for that session (If this data is important then we can show that. not sure)
              -  View All (linked to Django-admin page to list all bills for that  session)
              - Progress Gaps - confused about it. what is it? (haven't looked at the code yet in billy)

4. Vote Event Page
    - On overview page of a particular state, we can have a button `View All` (linked to Django-admin page to list all vote events for that  state.)
    -  On Navbar dropdown, there will a list of all legislative sessions when the user clicks on any one of them then a new page will open and there will be info like:-
              - `Result Counts` (how many passed/failed etc.)
              - ???

5.  Combining Bills & Vote Events
      - On overview page of a particular state, we can have two buttons `View All` (linked to Django-admin page to list all bills/vote events for that  state.)
      - On Navbar dropdown, there will a list of all legislative sessions under `Sessions` tag. when the user clicks on any one of them then a new page will open and there will be info as described on 4th and 3rd points.
