### ISSUE TITLE
enhance existing python-opencivicdata name resolution tool

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#5]
details TBD

**Comment by mileswwatkins** [comment]
@jamesturk, can you 1) point @hiteshgarg14 to the existing name resolution tool and 2) describe what enhancements are needed? Thanks!

**Comment by hiteshgarg14** [comment]
@mileswwatkins @jamesturk 
Since we haven't discussed this one yet. So I just want to share my thoughts on implementation of this tool before start working on it. So here are some points. please provide feedback :)

**Current Status**:
 - `name resolution` URL is not responding because it is not jurisdiction specific and there are lots of bills sponsors, voters (not covered `memberships` objects yet.) for just 31 jurisdictions and current code use to display all of them on a single page.


**Improvements Needed**
  - make it jurisdiction specific 
  - legislative session specific (to make a small queryset, _need this one ??_)
  - Introduce unmatched memberships objects 
  - ??

**Future in new `admintools` app**
   - Let's break this tool into 3 sections (_why??_ ,because there are lots of BillSponsorship, PersonVote, membership objects and if we will display all of them in a single page then it will be slower.)
        - Resolve Unmatched `BillSponsorship` objects (only unmatched person sponsors will be displayed)
        - Resolve Unmatched `PersonVote` objects (only unmatched voters will be displayed)
        - Resolve Unmatched `Memberships` objects (only unmatched person-memberships will be displayed)

**What can be done?**
   1. We can do changes in current `python-opencivicdata` repo or
   2.  we can copy-paste the required part from there and implement this tool into these 3 categories.

_IMO we should go for 2nd option._

**Comment by mileswwatkins** [comment]
Discussed the above just now, and it sounds great! With pagination, the load shouldn't be so bad.

We're planning to develop in this repo for now, and then we can merge this feature back into Python–OCD later, if the logic would be useful to non-OS projects.
