### ISSUE TITLE
Handle the deletion of data quality issues

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#52]
Spun off from @hiteshgarg14's thoughts in this comment: https://github.com/openstates/admintools/pull/43#issuecomment-317282434

@hiteshgarg14, does this happen just for name resolution, or for all data quality issues that are fixed by admin edits and/or patches?

@jamesturk, do you think we should delete _relevant_ data quality issues each time a fix is made? Or should we leave the counts as-is until the full `manage.py import all` is run again?

Personally, I'm in favor of having an AWS task that regularly performs the `import all`, or having a button in the nav bar to trigger an AWS task to do so (and otherwise it wouldn't happen besides on-pupa-import). That way we wouldn't need to keep track of which DQ issues have been solved by any given admin action or patch.

**Comment by hiteshgarg14** [comment]
@mileswwatkins yeah! this happens just for name resolution tool. If we run `manage.py resolve issues` then the corresponding data quality issue will get deleted.

**Comment by jamesturk** [comment]
I may need a summary of this issue, found the conversation a bit confusing up to here.

If I understand correctly:
- when you fix an issue (via accepting a fix) the DataQualityIssue is not deleted
- this means you need to wait until a count runs again
- but they aren't deleted before being imported, so they remain?

if so, I think the bug here is that they aren't deleted before being imported

if there's a task that can be run to update the counts (import all) how expensive is it to run for the given jurisdiction/issue type?  could we trigger a run of that after a save is done by an admin?

(and in general, I'm 👎 on tying this to AWS in any way, seems like a violation of separation of concerns)

**Comment by hiteshgarg14** [comment]
Actually, we fix issues by two things
1. By using `Resolvers`
2. By using Name Resolution Tool

Case 1:
  - when we create patches to fix data quality issues than on approving a patch the `count` will not get updated. because
     - admin may have accidentally marked the patch as `approved` and admin may want to change the status again. so it's not a good idea to delete the corresponding data quality issue at the time of reviewing a patch. that's why there is a code to delete the related data quality issues when we are actually applying the patches ie, when we run `python manage.py resolve issues` command.

Case 2:
   - When we manually match unmatched legislators to original `person` objects then, for now, there is no code to delete the related data quality issue.
   - Possible solutions:- [Link](https://github.com/openstates/admintools/pull/43#issuecomment-317282434)

@jamesturk so I think first 2 points out of 3 (from your comment above) are more related to `Case 1`
and 3rd point is related to `Case 2`


> if so, I think the bug here is that they aren't deleted before being imported

^^  is related to Possible Solution [1](https://github.com/openstates/admintools/pull/43#issuecomment-317282434)

> could we trigger a run of that after a save is done by an admin?

^^  is related to Possible Solution [2](https://github.com/openstates/admintools/pull/43#issuecomment-317282434)

**Comment by jamesturk** [comment]
OK thanks, I think we all agree now that Possible Solution 1 (delete DQ issues when running the management command) is the right answer
